### ISSUE TITLE
initscript is executed before images have been loaded

### ISSUE THREAD

**Issue by BernhardWerner** [CindyJS/CindyJS#847] opened 2021-02-10 20:08 UTC
What is says in the title: The function `imagesize("image name")` returns `[NaN, NaN]`.

**Comment by kortenkamp** [comment] 2021-02-10 20:14
Can you provide an example? Or rather: Are you sure that the image is indeed available? What is `imageready("image name")`?

**Comment by BernhardWerner** [comment] 2021-02-10 20:21
I can draw the image with `drawimage` without any problems. But `imageready` does indeed return `false`!

**Comment by kortenkamp** [comment] 2021-02-10 20:24
Well, the corresponding code to load images is in Setup.js:492. Maybe you can have a look there what is going wrong. Unfortunately without an example it is difficult to track this down.

**Comment by BernhardWerner** [comment] 2021-02-10 20:31
So, apparently the image isn't loaded before the init script is executed. Is that intended? In the draw script, `imageready` returns `true` and `imagesize` the correct resolution.

My use case is to create a second image the same size as a loaded image and then manipulate it with a shader via CindyGL.

Concerning an example:
```
<script id='init' type='text/x-cindyscript'>
println(imagesize("img1"));
</script>
<script>
  cindy = createCindy({canvasname:"CSCanvas",
                initscript:"init",
                images: {
                   img1: "img1.png",
                   img2: "img2.png"
                }
               });
</script>
```
shows the faulty/unexpected behaviour.

**Comment by kortenkamp** [comment] 2021-02-10 20:34
I think it should be expected that the images are loaded before the init script is executed. Is `image size("img1")` returning `[NaN, NaN]` also when called in the draw script?

**Comment by BernhardWerner** [comment] 2021-02-10 20:36
In the draw script it returns the correct image resolution.

**Comment by kortenkamp** [comment] 2021-02-10 21:01
ok, this should be easy to fix by moving line 409 in Setup.js (and 415, while we are at it) to line 426. I do not have time to do and test a proper fix, but you are invited to submit a merge request, I will quickly approve it.

**Comment by montaga** [comment] 2021-02-11 11:24
Likely the problem is related to asynchronous loading images. We cannot predict whether an image has been loaded before executing the init script. It is quite common on the web that parts of the website are rendered and can be used though not all contents are loaded.

CindyJS currently (aside from the bug that there are NaNs and no nadas, fixed by @strobelm in #848 ) reflects this behavior. It is a design question to change this behavior such that a user has to wait for an applet to become visible later until all images are loaded. Changing this would simplify programming applets accessing the images in the `init` script. However, it could run in long waiting times if big data, for instance, videos or huge DICOM-data (this happens in http://interactive.app.tum.de/web/09_ME/2 ) is loaded. In particular, accessing the webcam needs user interaction to be ready for use in CindyJS - in this case, having the applet blocked is likely not wanted - Better designed applets would inform by themself the user to allow access to its webcam etc.

The creator of a CindyJS-applet can use ``loaded=false`` in the `init` script and ```if(imageready("img1") & !loaded, loaded=true; println(imagesize("img1"));``` in the `draw` script.
This is indeed a bit cumbersome (and the `imageready` function seems not to be documented as well...). Callbacks would be the js-way out, but they are not supported in CindyScript. We could introduce a `imageloaded`-script which is executed once all images have been loaded for this purpose.

**Comment by kortenkamp** [comment] 2021-02-11 11:28
We could also allow a parameter `lazystart` that manages whether the init script will wait for loading images or not

**Comment by montaga** [comment] 2021-02-11 11:29
Another more user-friendly idea would be that `imagesize` waits until the image has been loaded. So running imagesize could block the applet, but in most cases the applets still remain fast and with advanced programming using `imageready` the old behavior could be still used.

**Closed** 2021-02-26 08:36 UTC
