### ISSUE TITLE
How to convert the degree operator: ‹number›° and to number (float)?

### ISSUE THREAD

**Issue by q2apro** [CindyJS/CindyJS#801] opened 2019-06-26 06:13 UTC
I am using a custom function that receives values that might be of type `number` or `number°`.

*I wouldl like to check in the beginning of the function what `type of` the variable is. I could not find a function for this in CindyJS.*

I mainly need to be consistent and transform all incoming values to their **float value (number)**. Without the degree. (NOT radians).

Examples: 
90° → 90
45 → 45
120° → 120

How can I do this?

**Comment by kortenkamp** [comment] 2019-06-26 07:04
The degree operator is not a different type. Angles in Cindy are complex numbers, as are distances or any other number.  Putting a ° behind a number just divides by 180 and multiplies by pi. 

Internally, at least in Cinderella, numbers have information about their usage, and if you use the degree postfix operator the number will be marked as an angle. But you cannot access this information.

To solve your problem: if you just evaluate the number, it will be a float number. Can you give a minimum working example where this does not work for you?

**Comment by q2apro** [comment] 2019-06-26 11:06
> Putting a ° behind a number just divides by 180 and multiplies by pi.

Thanks for this info. Please add it to the docs.

Accordingly, if I want the value as a float numer, I should do: **val° * 180 / pi**?

> if you just evaluate the number, it will be a float number, but in radians (...) just divide by 1°

Perfect! That should go to the docs too :)

I posted my problem in Mathelounge: https://www.mathelounge.de/642821/rotationswinkel-einzuzeichnende-dreieckswinkel-dreieckspunkte

I used arctan() in CindyJS, which returned angles. Putting those angles into the anglemark() function did not work:

```
anglemark(P, degstart, degend, r, line, fillcolor, fillalpha) := (
	// degstart can be number or number°, convert ?!
	zA = P + polar(degstart°);
	zB = P + polar(degend°);
	d = det(P,zA,zB);
	shape = if(
		d~=0,
		halfplane(join(P,zA), P+[ [0,-1], [1,0] ]*(zA-P)),
		if(
			d>0,
			halfplane(join(P,zA),zB)~~halfplane(join(P,zB),zA),
			screen()--(halfplane(join(P,zA),zB)~~halfplane(join(P,zB),zA))
		)
	)~~circle(P,r);
	fill(shape, alpha->fillalpha, color->fillcolor);
	if(line, draw(shape));
);
```

So in the beginning of the function I need to know if degree or rad.

**Comment by kortenkamp** [comment] 2019-06-26 11:24
It is in the docs (and has been for years), see https://docs.cinderella.de/tiki-index.php?page=Arithmetic+Operators . And dividing by 1° is giving you the measurement of any angle with 1° as a unit – I don't know why to put this in the docs, its basic maths, isn't it? If you want the number of quarter turns of any angle, you have to divide by 90°, analogously.

For your code problem: I recommend to assume that all angles are given in radians, all the time – as is the case in Cinderella. Then you don't have to put in the °. If you want to allow `anglemark(P, 45 ,90, 1,true,(0,0,0),1);` then you need it, but it would be semantically better to ask users to enter the ° if they want to specify degrees.

However… there is a clever workaround in (classic) Cinderella that caters for people who are unable to type ° (it's difficult to reach on US keyboards). What we do in text input fields for an angle `a` is that we check whether `a°` is an integer value. If so, it's highly likely that the user wanted to specify the angle in degrees instead of radians, and we use `a°`. If not, we use `a`. That solved the problem quite nicely (and I'm still proud of that solution ;-) ).

I'll close the issue now, feel free to reopen or file a new one if the problem is not solved for you.

**Closed by kortenkamp** 2019-06-26 11:24 UTC
