### ISSUE TITLE
Custom modifiers

### ISSUE THREAD

**Issue by BernhardWerner** [CindyJS/CindyJS#839] opened 2020-12-11 13:27 UTC
Is it possible to give the user the possibility to define their own modifiers when defining their functions?

There is a workaround thanks to overloading, but it's extremely clunky.

**Comment by BernhardWerner** [comment] 2021-07-27 07:37
Been a while since I asked, so: Is this feasible? If not, can someone explain to me why?

**Comment by kortenkamp** [comment] 2021-07-27 07:47
There is a way to define own modifiers in Cinderella (the Java version), but I have to admit that I never use it as I cannot remember the exact syntax. Maybe @richter-gebert can comment on this?

**Comment by kortenkamp** [comment] 2021-12-12 10:15
Closing this as a duplicate of #827

**Closed by kortenkamp** 2021-12-12 10:15 UTC
Labels: duplicate
