### ISSUE TITLE
CindyJS window size

### ISSUE THREAD

**Issue by JHM27** [CindyJS/CindyJS#522] opened 2016-10-25 08:54 UTC
The window size seems to depend on the existence of some object near the boundary  in order to make it full screen. So plot only uses the default small window size, it seems

**Comment by gagern** [comment] 2016-10-25 09:34
It's unclear to me what setup you're working with. Full screen as in full browser window, exported from Cinderella? Could it be that you're just seeing #471 which is a known bug causing plot to not use the full width of the viewport?

**Comment by JHM27** [comment] 2016-10-25 18:12
Aha, That sounds right

I am having a lot of trouble.

For example, I cannot select a point without actually moving it. Its name doesn’t appear in the Information window where it is expected.

JohnM


On 25 Oct 2016, at 10:34, Martin von Gagern <notifications@github.com<mailto:notifications@github.com>> wrote:


It's unclear to me what setup you're working with. Full screen as in full browser window, exported from Cinderella? Could it be that you're just seeing #471<https://github.com/CindyJS/CindyJS/issues/471> which is a known bug causing plot to not use the full width of the viewport?

**Comment by gagern** [comment] 2016-10-25 19:00
I'm closing this as a duplicate of #471 for now. Feel free to post subsequent bug reports for specific bugs as you encounter them. But “Information window” sounds a lot like Cinderella, and anything which doesn't show up there would very likely be a Cinderella issue, not a CindyJS one.

**Closed by gagern** 2016-10-25 19:00 UTC
